[package]
name = "rust_osero"
version = "0.1.0"
authors = ["TomoProg <helloworld0306.xxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
